### ISSUE TITLE
Shouldn't `Use &operator=(const Use & &use)` remove itself from the use list of the origin value?

### ISSUE THREAD

**Issue by ipChrisLee** [MaxXSoft/YuLang#1]
I think [copy assignment operator of `Use`](https://github.com/MaxXSoft/YuLang/blob/master/src/mid/usedef.h#LL149C1-L158C4) should be like this:
```c++
  // copy assignment operator
  Use &operator=(const Use &use) {
    if (this != &use) {
      if(value_) value_.RemoveUse(this);
      value_ = use.value_;
      user_ = use.user_;
      // update reference
      if (value_) value_->AddUse(this);
    }
    return *this;
  }
```
since after copy assignment operator, the origin `Value` is no longer used by origin `Use`.

Looking forward to your response at your earliest convenience.

**Comment by MaxXSoft** [comment]
Yes, you are right.

This issue has already been fixed in YuLang compiler's successor: [MimiC](https://github.com/ustb-owl/MimiC/blob/master/src/mid/usedef.h#L150-L157). Like this:

```cpp

  // copy assignment operator
  Use &operator=(const Use &use) {
    if (this != &use) {
      // update reference
      set_value(use.value_);
      user_ = use.user_;
    }
    return *this;
  }
```

Since YuLang compiler does almost nothing in its optimizer (almost all optimizations are done in LLVM), this issue has no serious impact.

Thank you for pointing this out, I'll fix it later.

**Comment by ipChrisLee** [comment]
> Yes, you are right.
> 
> This issue has already been fixed in YuLang compiler's successor: [MimiC](https://github.com/ustb-owl/MimiC/blob/master/src/mid/usedef.h#L150-L157). Like this:
> 
> ```c++
>   // copy assignment operator
>   Use &operator=(const Use &use) {
>     if (this != &use) {
>       // update reference
>       set_value(use.value_);
>       user_ = use.user_;
>     }
>     return *this;
>   }
> ```
> 
> Since YuLang compiler does almost nothing in its optimizer (almost all optimizations are done in LLVM), this issue has no serious impact.
> 
> Thank you for pointing this out, I'll fix it later.

I see, thanks for your brilliant reply.
